
<!DOCTYPE HTML>

<html lang="en" class="_theme-default">

<head>
  <meta charset="utf-8">
  <title>Function-try-block - C++ - W3cubDocs</title>
  
  <meta name="description" content=" Establishes an exception handler around the body of a function. ">
  <meta name="keywords" content="function-try-block, c++, cpp">
  <meta name="HandheldFriendly" content="True">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="mobile-web-app-capable" content="yes">
  
  <link rel="canonical" href="https://docs.w3cub.com/cpp/language/function-try-block.html">
  <link href="/favicon.png" rel="icon">
  <link rel="stylesheet" type="text/css" href="/assets/application-9c7b0d969c0ce639a6c01c2badcdd81667c7c66206aa3d0fccc5cb0585fb1b912dab72ea882101d18010680927514b4b77b107282db8f756fbf63301fe9c88b0.css">
  <script type="text/javascript" src="/assets/application-79c555f6b25481fffac2cac30a7f3e54e608ca09e9e8e42bb1790095ba6d0fcace47d6bc624ddce952c70370892f2d46864f89e6943d4f7f7ff16c8a3231a91a.js"></script>
  <script src="/json/cpp.js"></script>
  
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-R3WC07G3GB"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'G-R3WC07G3GB');
</script>
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-2572770204602497"
     crossorigin="anonymous"></script>
<script async custom-element="amp-auto-ads"
  src="https://cdn.ampproject.org/v0/amp-auto-ads-0.1.js">
</script>


</head>

<body class="docs">
	<amp-auto-ads type="adsense"
              data-ad-client="ca-pub-2572770204602497">
	</amp-auto-ads>
	<div class="_app">
	<header class="_header">

  <a class="_home-link" href="/" ></a>
  <a class="_menu-link"></a>
  <h1 class="_logo">
    <a href="/" class="_nav-link" title="API Documentation Browser">W3cubDocs</a>
  </h1>
  
  <span class="_logo-sub-nav">/</span><span class="_logo-sub-nav"><a href="/cpp/" class="_nav-link" title="" style="margin-left:0;">C++</a></span>
  
  <nav class="_nav">
    <a href="https://tools.w3cub.com/?_sp=docs" target="_blank" class="_nav-link ">W3cubTools</a>
    <a href="/cheatsheets/" class="_nav-link ">Cheatsheets</a>
    <a href="/about/" class="_nav-link ">About</a>
  </nav>
</header>
	<section class="_sidebar">
		
		<form class="_search">
		  <input type="search" class="_search-input" placeholder="Search&hellip;" autocomplete="off" autocapitalize="off" autocorrect="off" spellcheck="false" maxlength="20">
		  <a class="_search-clear"></a>
		  <div class="_search-tag"></div>
		</form>
		
		<div class="_list-wrap">
			<div class="_list">
			
			</div>
		</div>
	</section>
	<section class="_container ">
		<div class="_content">
			<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-2572770204602497"
     data-ad-slot="6861657091"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
			<div class="_page _cppref">
				
				
<h1 id="firstHeading" class="firstHeading">Function-try-block</h1>            <p>Establishes an exception handler around the body of a function.</p>
<h3 id="Syntax"> Syntax</h3> <p>The function-try-block is one of the alternative syntax forms for <span class="t-spar">function-body</span>, which is a part of <a href="function" title="cpp/language/function">function definition</a>.</p>
<table class="t-sdsc-begin">  <tr class="t-sdsc"> <td class="t-sdsc-nopad"> <code>try</code> <span class="t-spar">ctor-initializer</span> ï»¿<span class="t-mark">(optional)</span> <span class="t-spar">compound-statement</span> <span class="t-spar">handler-sequence</span> </td> <td class="t-sdsc-nopad"> </td> <td class="t-sdsc-nopad"> </td>
</tr> 
</table> <table class="t-par-begin"> <tr class="t-par"> <td> <span class="t-spar">ctor-initializer</span> </td> <td> - </td> <td> member <a href="initializer_list" title="cpp/language/initializer list" class="mw-redirect">initializer list</a>, only allowed in constructors </td>
</tr> <tr class="t-par"> <td> <span class="t-spar">compound-statement</span> </td> <td> - </td> <td> the brace-enclosed <a href="statements#Compound_statements" title="cpp/language/statements">sequence of statements</a> that constitutes the body of a function </td>
</tr> <tr class="t-par"> <td> <span class="t-spar">handler-sequence</span> </td> <td> - </td> <td> sequence of one or more <a href="try_catch" title="cpp/language/try catch">catch-clauses</a> </td>
</tr>
</table> <h3 id="Explanation"> Explanation</h3> <p>A <i>function-try-block</i> associates a sequence of catch clauses with the entire function body, and with the <a href="initializer_list" title="cpp/language/initializer list" class="mw-redirect">member initializer list</a> (if used in a constructor) as well. Every exception thrown from any statement in the function body, or (for constructors) from any member or base constructor, or (for destructors) from any member or base destructor, transfers control to the <span class="t-spar">handler-sequence</span> the same way an exception thrown in a regular <a href="try_catch" title="cpp/language/try catch">try block</a> would.</p>
<div class="t-example"> <div class="cpp source-cpp"><pre data-language="cpp">#include &lt;iostream&gt;
#include &lt;string&gt;
 
struct S
{
    std::string m;
 
    S(const std::string&amp; str, int idx)
    try : m(str, idx)
    {
        std::cout &lt;&lt; "S(" &lt;&lt; str &lt;&lt; ", " &lt;&lt; idx &lt;&lt; ") constructed, m = " &lt;&lt; m &lt;&lt; '\n';
    }
    catch(const std::exception&amp; e)
    {
        std::cout &lt;&lt; "S(" &lt;&lt; str &lt;&lt; ", " &lt;&lt; idx &lt;&lt; ") failed: " &lt;&lt; e.what() &lt;&lt; '\n';
    } // implicit "throw;" here for constructor
};
 
int main()
{
    S s1{"ABC", 1}; // does not throw (index is in bounds)
 
    try
    {
        S s2{"ABC", 4}; // throws (out of bounds)
    }
    catch (std::exception&amp; e)
    {
        std::cout &lt;&lt; "S s2... raised an exception: " &lt;&lt; e.what() &lt;&lt; '\n';
    }
}</pre></div> </div> <p>Before any catch clauses of a function-try-block on a constructor are entered, all fully-constructed members and bases have already been destroyed.</p>
<table class="t-rev-begin"> <tr class="t-rev t-since-cxx11">
<td> <p>If the function-try-block is on a delegating constructor, which called a non-delegating constructor that completed successfully, but then the body of the delegating constructor throws, the destructor of this object will be completed before any catch clauses of the function-try-block are entered.</p>
</td> <td><span class="t-mark-rev t-since-cxx11">(since C++11)</span></td>
</tr> </table> <p>Before any catch clauses of a function-try-block on a destructor are entered, all bases and non-variant members have already been destroyed.</p>
<p>The behavior is undefined if the catch-clause of a function-try-block used on a constructor or a destructor accesses a base or a non-static member of the object.</p>
<p>Every catch-clause in the function-try-block for a constructor must terminate by throwing an exception. If the control reaches the end of such handler, the current exception is automatically rethrown as if by <code>throw;</code>. The return statement is not allowed in any catch clause of a constructor's function-try-block.</p>
<p>Reaching the end of a catch clause for a function-try-block on a destructor also automatically rethrows the current exception as if by <code>throw;</code>, but a return statement is allowed.</p>
<p>For all other functions, reaching the end of a catch clause is equivalent to <code>return;</code> if the function's return type is (possibly cv-qualified) <code>void</code>, otherwise the behavior is undefined.</p>
<h3 id="Notes"> Notes</h3> <p>The primary purpose of function-try-blocks is to respond to an exception thrown from the member initializer list in a constructor by logging and rethrowing, modifying the exception object and rethrowing, throwing a different exception instead, or terminating the program. They are rarely used with destructors or with regular functions.</p>
<p>Function-try-block does not catch the exceptions thrown by the copy/move constructors and the destructors of the function parameters passed by value: those exceptions are thrown in context of the caller.</p>
<table class="t-rev-begin"> <tr class="t-rev t-since-cxx11">
<td> Function-try-block of the top-level function of a thread does not catch the exceptions thrown from the constructors and destructors of <a href="storage_duration" title="cpp/language/storage duration">thread-local</a> objects (except for the constructors of function-scoped thread-locals). </td> <td><span class="t-mark-rev t-since-cxx11">(since C++11)</span></td>
</tr> </table> <p>Likewise, function-try-block of the <a href="main_function" title="cpp/language/main function">main() function</a> does not catch the exceptions thrown from the constructors and destructors of <a href="storage_duration" title="cpp/language/storage duration">static</a> objects (except for the constructors of function-local statics).</p>
<p><a href="scope#Block_scope" title="cpp/language/scope">The scope</a> and lifetime of the function parameters (but not any objects declared in the function itself), extend to the end of the <span class="t-spar">handler-sequence</span>.</p>
<div class="cpp source-cpp"><pre data-language="cpp">int f(int n = 2) try
{
    ++n; // increments the function parameter
    throw n;
}
catch(...)
{
    ++n; // n is in scope and still refers to the function parameter
    assert(n == 4);
    return n;
}</pre></div> <h3 id="Defect_reports"> Defect reports</h3> <p>The following behavior-changing defect reports were applied retroactively to previously published C++ standards.</p>
<table class="dsctable"> <tr> <th> DR </th> <th> Applied to </th> <th> Behavior as published </th> <th> Correct behavior </th>
</tr> <tr> <td> <a rel="nofollow" class="external text" href="https://cplusplus.github.io/CWG/issues/1167.html">CWG 1167</a> </td> <td> C++98 </td> <td> it was unspecified whether a function-try-block on a destructor<br>will catch exceptions from a base or member destructor </td> <td> such exceptions are caught </td>
</tr>
</table>           <div class="_attribution">
  <p class="_attribution-p">
    Â© cppreference.com<br>Licensed under the Creative Commons Attribution-ShareAlike Unported License v3.0.<br>
    <a href="https://en.cppreference.com/w/cpp/language/function-try-block" class="_attribution-link">https://en.cppreference.com/w/cpp/language/function-try-block</a>
  </p>
</div>

				
			</div>
			<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-2572770204602497"
     data-ad-slot="1992473792"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
		</div>
	</section>

	</div>
	<svg style="display:none">
		<symbol id="icon-dir"><svg viewBox="0 0 20 20"><path d="M15 10c0 .3-.305.515-.305.515l-8.56 5.303c-.625.41-1.135.106-1.135-.67V4.853c0-.777.51-1.078 1.135-.67l8.56 5.305S15 9.702 15 10z"/></svg></symbol>
	  </svg>
</body>
</html>
