
<!DOCTYPE HTML>

<html lang="en" class="_theme-default">

<head>
  <meta charset="utf-8">
  <title>Std&#58;&#58;current_exception - C++ - W3cubDocs</title>
  
  <meta name="description" content="If called during exception handling (typically, in a catch clause), captures the current exception object and creates an std&#58;&#58;exception_ptr &hellip;">
  <meta name="keywords" content="std, current, exception, c++, cpp">
  <meta name="HandheldFriendly" content="True">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="mobile-web-app-capable" content="yes">
  
  <link rel="canonical" href="https://docs.w3cub.com/cpp/error/current_exception.html">
  <link href="/favicon.png" rel="icon">
  <link rel="stylesheet" type="text/css" href="/assets/application-9c7b0d969c0ce639a6c01c2badcdd81667c7c66206aa3d0fccc5cb0585fb1b912dab72ea882101d18010680927514b4b77b107282db8f756fbf63301fe9c88b0.css">
  <script type="text/javascript" src="/assets/application-79c555f6b25481fffac2cac30a7f3e54e608ca09e9e8e42bb1790095ba6d0fcace47d6bc624ddce952c70370892f2d46864f89e6943d4f7f7ff16c8a3231a91a.js"></script>
  <script src="/json/cpp.js"></script>
  
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-R3WC07G3GB"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'G-R3WC07G3GB');
</script>
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-2572770204602497"
     crossorigin="anonymous"></script>
<script async custom-element="amp-auto-ads"
  src="https://cdn.ampproject.org/v0/amp-auto-ads-0.1.js">
</script>


</head>

<body class="docs">
	<amp-auto-ads type="adsense"
              data-ad-client="ca-pub-2572770204602497">
	</amp-auto-ads>
	<div class="_app">
	<header class="_header">

  <a class="_home-link" href="/" ></a>
  <a class="_menu-link"></a>
  <h1 class="_logo">
    <a href="/" class="_nav-link" title="API Documentation Browser">W3cubDocs</a>
  </h1>
  
  <span class="_logo-sub-nav">/</span><span class="_logo-sub-nav"><a href="/cpp/" class="_nav-link" title="" style="margin-left:0;">C++</a></span>
  
  <nav class="_nav">
    <a href="https://tools.w3cub.com/?_sp=docs" target="_blank" class="_nav-link ">W3cubTools</a>
    <a href="/cheatsheets/" class="_nav-link ">Cheatsheets</a>
    <a href="/about/" class="_nav-link ">About</a>
  </nav>
</header>
	<section class="_sidebar">
		
		<form class="_search">
		  <input type="search" class="_search-input" placeholder="Search&hellip;" autocomplete="off" autocapitalize="off" autocorrect="off" spellcheck="false" maxlength="20">
		  <a class="_search-clear"></a>
		  <div class="_search-tag"></div>
		</form>
		
		<div class="_list-wrap">
			<div class="_list">
			
			</div>
		</div>
	</section>
	<section class="_container ">
		<div class="_content">
			<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-2572770204602497"
     data-ad-slot="6861657091"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
			<div class="_page _cppref">
				
				
<h1 id="firstHeading" class="firstHeading">std::current_exception</h1>            <table class="t-dcl-begin"> <tr class="t-dsc-header"> <th> Defined in header <code><a href="../header/exception" title="cpp/header/exception">&lt;exception&gt;</a></code> </th> <th> </th> <th> </th> </tr> <tr class="t-dcl t-since-cxx11"> <td> <pre data-language="cpp">std::exception_ptr current_exception() noexcept;</pre>
</td> <td class="t-dcl-nopad"> </td> <td> <span class="t-mark-rev t-since-cxx11">(since C++11)</span> </td> </tr>  </table> <p>If called during exception handling (typically, in a <code>catch</code> clause), captures the current exception object and creates an <code><a href="exception_ptr" title="cpp/error/exception ptr">std::exception_ptr</a></code> that holds either a copy or a reference to that exception object (depending on the implementation). The referenced object remains valid at least as long as there is an <code>exception_ptr</code> object that refers to it.</p>
<p>If the implementation of this function requires a call to <code>new</code> and the call fails, the returned pointer will hold a reference to an instance of <code><a href="../memory/new/bad_alloc" title="cpp/memory/new/bad alloc">std::bad_alloc</a></code>.</p>
<p>If the implementation of this function requires copying the captured exception object and its copy constructor throws an exception, the returned pointer will hold a reference to the exception thrown. If the copy constructor of the thrown exception object also throws, the returned pointer may hold a reference to an instance of <code><a href="bad_exception" title="cpp/error/bad exception">std::bad_exception</a></code> to break the endless loop.</p>
<p>If the function is called when no exception is being handled, an empty <code><a href="exception_ptr" title="cpp/error/exception ptr">std::exception_ptr</a></code> is returned.</p>
<p>This function can be called in a <code><a href="terminate_handler" title="cpp/error/terminate handler">std::terminate_handler</a></code> to retrieve the exception which has provoked the invocation of <code><a href="terminate" title="cpp/error/terminate">std::terminate</a></code>.</p>
<h3 id="Parameters"> Parameters</h3> <p>(none).</p>
<h3 id="Return_value"> Return value</h3> <p>An instance of <code><a href="exception_ptr" title="cpp/error/exception ptr">std::exception_ptr</a></code> holding a reference to the exception object, or a copy of the exception object, or to an instance of <code><a href="../memory/new/bad_alloc" title="cpp/memory/new/bad alloc">std::bad_alloc</a></code> or to an instance of <code><a href="bad_exception" title="cpp/error/bad exception">std::bad_exception</a></code>.</p>
<h3 id="Notes"> Notes</h3> <p>On the implementations that follow <a rel="nofollow" class="external text" href="https://itanium-cxx-abi.github.io/cxx-abi/abi.html">Itanium C++ ABI</a> (GCC, Clang, etc), exceptions are allocated on the heap when thrown (except for <code><a href="../memory/new/bad_alloc" title="cpp/memory/new/bad alloc">std::bad_alloc</a></code> in some cases), and this function simply creates the smart pointer referencing the previously-allocated object, On MSVC, exceptions are allocated on stack when thrown, and this function performs the heap allocation and copies the exception object.</p>
<p>On Windows in managed CLR environments <a rel="nofollow" class="external autonumber" href="https://learn.microsoft.com/en-us/cpp/dotnet/exceptions-in-cpp-cli">[1]</a>, the implementation will store a <code><a href="bad_exception" title="cpp/error/bad exception">std::bad_exception</a></code> when the current exception is a managed exception (<a rel="nofollow" class="external autonumber" href="https://github.com/microsoft/STL/blob/65aab97a8e75e7ba409002e518ed799006dfb285/stl/src/excptptr.cpp#L367">[2]</a>). Note that <code>catch(...)</code> catches also managed exceptions:</p>
<div class="cpp source-cpp"><pre data-language="cpp">#include &lt;exception&gt;
 
int main()
{
    try
    {
        throw gcnew System::Exception("Managed exception");
    }
    catch (...)
    {
        std::exception_ptr ex = std::current_exception();
        try
        {
            std::rethrow_exception(ex);
        }
        catch (std::bad_exception const &amp;)
        {
            // This will be printed.
            std::cout &lt;&lt; "Bad exception" &lt;&lt; std::endl;
        }
    }
}</pre></div> <h3 id="Example"> Example</h3> 
<div class="t-example"> <div class="cpp source-cpp"><pre data-language="cpp">#include &lt;exception&gt;
#include &lt;iostream&gt;
#include &lt;stdexcept&gt;
#include &lt;string&gt;
 
void handle_eptr(std::exception_ptr eptr) // passing by value is ok
{
    try
    {
        if (eptr)
            std::rethrow_exception(eptr);
    }
    catch(const std::exception&amp; e)
    {
        std::cout &lt;&lt; "Caught exception: '" &lt;&lt; e.what() &lt;&lt; "'\n";
    }
}
 
int main()
{
    std::exception_ptr eptr;
 
    try
    {
        std::string().at(1); // this generates a std::out_of_range
    }
    catch(...)
    {
        eptr = std::current_exception(); // capture
    }
 
    handle_eptr(eptr);
 
} // destructor for std::out_of_range called here, when the eptr is destructed</pre></div> <p>Possible output:</p>
<div class="text source-text"><pre data-language="c">Caught exception: 'basic_string::at: __n (which is 1) &gt;= this-&gt;size() (which is 0)'</pre></div> </div> <h3 id="See_also"> See also</h3> <table class="t-dsc-begin"> <tr class="t-dsc"> <td> <div><a href="exception_ptr" title="cpp/error/exception ptr"> <span class="t-lines"><span>exception_ptr</span></span></a></div>
<div><span class="t-lines"><span><span class="t-mark-rev t-since-cxx11">(C++11)</span></span></span></div> </td> <td> shared pointer type for handling exception objects <br> <span class="t-mark">(typedef)</span>  </td>
</tr> <tr class="t-dsc"> <td> <div><a href="rethrow_exception" title="cpp/error/rethrow exception"> <span class="t-lines"><span>rethrow_exception</span></span></a></div>
<div><span class="t-lines"><span><span class="t-mark-rev t-since-cxx11">(C++11)</span></span></span></div> </td> <td> throws the exception from an <code><a href="exception_ptr" title="cpp/error/exception ptr">std::exception_ptr</a></code> <br> <span class="t-mark">(function)</span>  </td>
</tr> <tr class="t-dsc"> <td> <div><a href="make_exception_ptr" title="cpp/error/make exception ptr"> <span class="t-lines"><span>make_exception_ptr</span></span></a></div>
<div><span class="t-lines"><span><span class="t-mark-rev t-since-cxx11">(C++11)</span></span></span></div> </td> <td> creates an <code><a href="exception_ptr" title="cpp/error/exception ptr">std::exception_ptr</a></code> from an exception object <br> <span class="t-mark">(function template)</span>  </td>
</tr> <tr class="t-dsc"> <td> <div><a href="uncaught_exception" title="cpp/error/uncaught exception"> <span class="t-lines"><span>uncaught_exception</span><span>uncaught_exceptions</span></span></a></div>
<div><span class="t-lines"><span><span class="t-mark-rev t-until-cxx20">(removed in C++20)</span></span><span><span class="t-mark-rev t-since-cxx17">(C++17)</span></span></span></div> </td> <td> checks if exception handling is currently in progress <br> <span class="t-mark">(function)</span>  </td>
</tr> </table>           <div class="_attribution">
  <p class="_attribution-p">
    © cppreference.com<br>Licensed under the Creative Commons Attribution-ShareAlike Unported License v3.0.<br>
    <a href="https://en.cppreference.com/w/cpp/error/current_exception" class="_attribution-link">https://en.cppreference.com/w/cpp/error/current_exception</a>
  </p>
</div>

				
			</div>
			<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-2572770204602497"
     data-ad-slot="1992473792"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
		</div>
	</section>

	</div>
	<svg style="display:none">
		<symbol id="icon-dir"><svg viewBox="0 0 20 20"><path d="M15 10c0 .3-.305.515-.305.515l-8.56 5.303c-.625.41-1.135.106-1.135-.67V4.853c0-.777.51-1.078 1.135-.67l8.56 5.305S15 9.702 15 10z"/></svg></symbol>
	  </svg>
</body>
</html>
